<MainScreen>:
    size: root.width, root.height
    BoxLayout:
        id: main_box
        orientation: "vertical"
        MDTopAppBar:
            title: "Creados de horarios"
        MDScreenManager:
            id: manager
            FirstScreen:
            ListOfCoursesScreen:
            LoadScreen:
            ShowScreen:
            CacheScreen:
            ConfigScreen:
            CreateScreen:


<FirstScreen>:
    name: "first"

    MDRectangleFlatIconButton:
        text:"Crea tu horario"
        on_release: root.manager.current = "listofcourses"
        pos_hint: {"center_x": 0.5, "center_y": 0.8}
        icon: "calendar-month"

    MDRectangleFlatIconButton:
        text:"Cargar horarios desde tu caché"
        on_release: root.manager.current = "cache"
        pos_hint: {"center_x": 0.5, "center_y": 0.6}
        icon: "cached"

    MDRectangleFlatIconButton:
        text:"Configurar tu sistema de puntaje"
        on_release: root.manager.current = "config"
        pos_hint: {"center_x": 0.5, "center_y": 0.4}
        icon: "cog"

<ListOfCoursesScreen>:
    name: "listofcourses"
    BoxLayout:
        orientation:"vertical"
        size_hint_y: None  # Prevents stretching vertically
        height: self.minimum_height  # Wrap content height
        spacing: "40dp"
        pos_hint: {"center_x": 0.5, "top": 0.9}  # Moves it to the top
        MDLabel:
            halign: "center"
            theme_text_color: "Primary"
            text: "Quieres usar los cursos cargados anteriormente?"
        BoxLayout:
            orientation:"horizontal"
            size_hint: None, None
            size: self.minimum_size
            pos_hint: {"center_x": 0.5}
            spacing: "10dp"
            MDRectangleFlatButton:
                text: "Sí"
                on_release: root.manager.current = "load"
            MDRectangleFlatButton:
                text: "No"
                on_release: root.manager.current = "create"
    
    MDFloatLayout:
        size_hint_y: None
        height: 0.1 * root.height
        pos_hint: {"x": 0, "y": 0}
        padding: dp(10)
        MDIconButton:
            on_release: root.manager.current = "first"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            icon: "home"


<LoadScreen>:
    name: "load"
    BoxLayout:
        orientation:"vertical"
        size_hint_y: None  # Prevents stretching vertically
        height: self.minimum_height  # Wrap content height
        spacing: "40dp"
        pos_hint: {"center_x": 0.5, "top": 0.9}  # Moves it to the top
        MDLabel:
            halign: "center"
            id: statuslabel
            text: "0 %"
        BoxLayout:
            size_hint_y: None
            height: 20  # Adjust the height of the progress bar
            padding: dp(5)
            MDProgressBar:
                id: progress_bar
                size_hint_x: 0.5  # Adjust width (0.5 = 50% of parent width)
                pos_hint: {"center_x": 0.5}  # Center it horizontally
                value: 0
        
        MDRectangleFlatIconButton:
            id: startprogressbtn
            text:"Iniciar"
            on_release: root.start_loading()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            icon: "play"
            
    MDFloatLayout:
        size_hint_y: None
        height: 0.1 * root.height
        pos_hint: {"x": 0, "y": 0}
        padding: dp(10)
        MDIconButton:
            on_release: root.go_back()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            icon: "home"

<ShowScreen>:
    name: "show"
    MDBoxLayout:
        orientation: "vertical"
        MDScrollView:
            id:my_scrollview
            do_scroll_x: False
            do_scroll_y: True
            size_hint_y: None
            height: 0.9 * root.height
            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True  # Allows scrolling
                spacing: dp(10)  # Optional: Adds spacing between cards
                padding: dp(10)
                id: cards_box
        MDFloatLayout:
            size_hint_y: None
            height: 0.1 * root.height
            pos_hint: {"x": 0, "y": 0}
            padding: dp(10)
            
            MDLabel:
                id:total_calendars_label
                text: ""
                pos_hint: {"center_y": 0.5, "x": 0.05}
            MDIconButton:
                on_release: root.manager.current = "first"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                icon: "home"
                
            MDIconButton:
                on_release: root.go_back()
                pos_hint: {"center_x": 0.4, "center_y": 0.5}
                icon: "arrow-left"
            MDIconButton:
                on_release: root.go_next()
                pos_hint: {"center_x": 0.6, "center_y": 0.5}
                icon: "arrow-right"

<CacheScreen>:
    name: "cache"
    MDBoxLayout:
        orientation: "vertical"
        MDScrollView:
            id:my_scrollview
            do_scroll_x: False
            do_scroll_y: True
            size_hint_y: None
            height: 0.9 * root.height
            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True  # Allows scrolling
                spacing: dp(10)  # Optional: Adds spacing between cards
                padding: dp(10)
                id: btn_box
        MDFloatLayout:
            size_hint_y: None
            height: 0.1 * root.height
            pos_hint: {"x": 0, "y": 0}
            padding: dp(10)
            MDIconButton:
                on_release: root.manager.current = "first"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                icon: "home"
            MDRectangleFlatButton:
                on_release: root.cache_btn()
                pos_hint: {"center_x": 0.8, "center_y": 0.5}
                text: "Limpiar Caché"
            
<ConfigScreen>:
    name: "config"
    MDFloatLayout:
        size_hint_y: None
        height: 0.1 * root.height
        pos_hint: {"x": 0, "y": 0}
        padding: dp(10)
        MDIconButton:
            on_release: root.manager.current = "first"
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            icon: "home"
        MDRectangleFlatButton:
            on_release: root.reset_btn()
            pos_hint: {"center_x": 0.8, "center_y": 0.5}
            text: "Reiniciar Configuración"

<CreateScreen>:
    name: "create"
    MDBoxLayout:
        orientation: "vertical"
        CreateRecycleView:
            id: rv
        MDFloatLayout:
            size_hint_y: None
            height: 0.1 * root.height
            pos_hint: {"x": 0, "y": 0}
            padding: dp(10)
            MDIconButton:
                on_release: root.manager.current = "first"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                icon: "home"

<CreateRecycleView>:
    viewclass: "CreateBox"
    RecycleBoxLayout:
        default_size: None, 100
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"
<CreateBox>:
    size_hint_x: None
    width: root.width
    orientation: "horizontal"
    padding: dp(5)
    spacing: dp(10)
    MDTextField:
        id: entry
        size_hint_x: None
        multiline: False
        width: dp(80)
    MDRectangleFlatButton:
        pos_hint: {"center_x": 0.8} 
        text: "Añadir" + root.i
    MDRectangleFlatButton:
        id: removebtn
        pos_hint: {"center_x": 0.9} 
        text: root.eliminado
        on_release: root.i = "xD"
    